# -*- coding: utf-8 -*-
"""
Dicionario gerado automaticamente contendo a forma exata dos municipios
observados nos arquivos GeoJSON e suas respectivas Regioes de Integração.
"""

MAPA_MUNICIPIO_REGIAO = {
    "ABAETETUBA": "Região Tocantins",
    "ABEL FIGUEIREDO": "Região Rio Capim",
    "ACARÁ": "Região Tocantins",
    "AFUÁ": "Região Marajó",
    "ALENQUER": "Região Baixo Amazonas",
    "ALMEIRIM": "Região Baixo Amazonas",
    "ALTAMIRA": "Região Xingu",
    "ANAJÁS": "Região Marajó",
    "ANANINDEUA": "Região Guajará",
    "ANAPU": "Região Xingu",
    "AUGUSTO CORRÊA": "Região Rio Caeté",
    "AURORA DO PARÁ": "Região Rio Capim",
    "AVEIRO": "Região Tapajós",
    "BAGRE": "Região Marajó",
    "BAIÃO": "Região Tocantins",
    "BANNACH": "Região Araguaia",
    "BARCARENA": "Região Tocantins",
    "BELTERRA": "Região Baixo Amazonas",
    "BELÉM": "Região Guajará",
    "BENEVIDES": "Região Guajará",
    "BOM JESUS DO TOCANTINS": "Região Carajás",
    "BONITO": "Região Rio Caeté",
    "BRAGANÇA": "Região Rio Caeté",
    "BRASIL NOVO": "Região Xingu",
    "BREJO GRANDE DO ARAGUAIA": "Região Carajás",
    "BREU BRANCO": "Região Lago Tucuruí",
    "BREVES": "Região Marajó",
    "BUJARU": "Região Rio Capim",
    "CACHOEIRA DO ARARI": "Região Marajó",
    "CACHOEIRA DO PIRIÁ": "Região Rio Caeté",
    "CAMETÁ": "Região Tocantins",
    "CANAÃ DOS CARAJÁS": "Região Carajás",
    "CAPANEMA": "Região Rio Caeté",
    "CAPITÃO POÇO": "Região Rio Capim",
    "CASTANHAL": "Região Guamá",
    "CHAVES": "Região Marajó",
    "COLARES": "Região Guamá",
    "CONCEIÇÃO DO ARAGUAIA": "Região Araguaia",
    "CONCÓRDIA DO PARÁ": "Região Rio Capim",
    "CUMARU DO NORTE": "Região Araguaia",
    "CURIONÓPOLIS": "Região Carajás",
    "CURRALINHO": "Região Marajó",
    "CURUÁ": "Região Baixo Amazonas",
    "CURUÇÁ": "Região Guamá",
    "DOM ELISEU": "Região Rio Capim",
    "ELDORADO DO CARAJÁS": "Região Carajás",
    "FARO": "Região Baixo Amazonas",
    "FLORESTA DO ARAGUAIA": "Região Araguaia",
    "GARRAFÃO DO NORTE": "Região Rio Capim",
    "GOIANÉSIA DO PARÁ": "Região Lago Tucuruí",
    "GURUPÁ": "Região Marajó",
    "IGARAPÉ-AÇU": "Região Guamá",
    "IGARAPÉ-MIRI": "Região Tocantins",
    "INHANGAPI": "Região Guamá",
    "IPIXUNA DO PARÁ": "Região Rio Capim",
    "IRITUIA": "Região Rio Capim",
    "ITAITUBA": "Região Tapajós",
    "ITUPIRANGA": "Região Lago Tucuruí",
    "JACAREACANGA": "Região Tapajós",
    "JACUNDÁ": "Região Lago Tucuruí",
    "JURUTI": "Região Baixo Amazonas",
    "LIMOEIRO DO AJURU": "Região Tocantins",
    "MAGALHÃES BARATA": "Região Guamá",
    "MARABÁ": "Região Carajás",
    "MARACANÃ": "Região Guamá",
    "MARAPANIM": "Região Guamá",
    "MARITUBA": "Região Guajará",
    "MEDICILÂNDIA": "Região Xingu",
    "MELGAÇO": "Região Marajó",
    "MOCAJUBA": "Região Tocantins",
    "MOJU": "Região Tocantins",
    "MOJUÍ DOS CAMPOS": "Região Baixo Amazonas",
    "MONTE ALEGRE": "Região Baixo Amazonas",
    "MUANÁ": "Região Marajó",
    "MÃE DO RIO": "Região Rio Capim",
    "NOVA ESPERANÇA DO PIRIÁ": "Região Rio Capim",
    "NOVA IPIXUNA": "Região Lago Tucuruí",
    "NOVA TIMBOTEUA": "Região Rio Caeté",
    "NOVO PROGRESSO": "Região Tapajós",
    "NOVO REPARTIMENTO": "Região Lago Tucuruí",
    "OEIRAS DO PARÁ": "Região Tocantins",
    "ORIXIMINÁ": "Região Baixo Amazonas",
    "OURILÂNDIA DO NORTE": "Região Araguaia",
    "OURÉM": "Região Rio Capim",
    "PACAJÁ": "Região Xingu",
    "PALESTINA DO PARÁ": "Região Carajás",
    "PARAGOMINAS": "Região Rio Capim",
    "PARAUAPEBAS": "Região Carajás",
    "PAU D'ARCO": "Região Araguaia",
    "PEIXE-BOI": "Região Rio Caeté",
    "PIÇARRA": "Região Carajás",
    "PLACAS": "Região Xingu",
    "PONTA DE PEDRAS": "Região Marajó",
    "PORTEL": "Região Marajó",
    "PORTO DE MOZ": "Região Xingu",
    "PRAINHA": "Região Baixo Amazonas",
    "PRIMAVERA": "Região Rio Caeté",
    "QUATIPURU": "Região Rio Caeté",
    "REDENÇÃO": "Região Araguaia",
    "RIO MARIA": "Região Araguaia",
    "RONDON DO PARÁ": "Região Rio Capim",
    "RURÓPOLIS": "Região Tapajós",
    "SALINÓPOLIS": "Região Rio Caeté",
    "SALVATERRA": "Região Marajó",
    "SANTA BÁRBARA DO PARÁ": "Região Guajará",
    "SANTA CRUZ DO ARARI": "Região Marajó",
    "SANTA IZABEL DO PARÁ": "Região Guamá",
    "SANTA LUZIA DO PARÁ": "Região Rio Caeté",
    "SANTA MARIA DAS BARREIRAS": "Região Araguaia",
    "SANTA MARIA DO PARÁ": "Região Guamá",
    "SANTANA DO ARAGUAIA": "Região Araguaia",
    "SANTARÉM": "Região Baixo Amazonas",
    "SANTARÉM NOVO": "Região Rio Caeté",
    "SANTO ANTÔNIO DO TAUÁ": "Região Guamá",
    "SAPUCAIA": "Região Araguaia",
    "SENADOR JOSÉ PORFÍRIO": "Região Xingu",
    "SOURE": "Região Marajó",
    "SÃO CAETANO DE ODIVELAS": "Região Guamá",
    "SÃO DOMINGOS DO ARAGUAIA": "Região Carajás",
    "SÃO DOMINGOS DO CAPIM": "Região Guamá",
    "SÃO FRANCISCO DO PARÁ": "Região Guamá",
    "SÃO FÉLIX DO XINGU": "Região Araguaia",
    "SÃO GERALDO DO ARAGUAIA": "Região Carajás",
    "SÃO JOÃO DA PONTA": "Região Guamá",
    "SÃO JOÃO DE PIRABAS": "Região Rio Caeté",
    "SÃO JOÃO DO ARAGUAIA": "Região Carajás",
    "SÃO MIGUEL DO GUAMÁ": "Região Guamá",
    "SÃO SEBASTIÃO DA BOA VISTA": "Região Marajó",
    "TAILÂNDIA": "Região Tocantins",
    "TERRA ALTA": "Região Guamá",
    "TERRA SANTA": "Região Baixo Amazonas",
    "TOMÉ-AÇU": "Região Rio Capim",
    "TRACUATEUA": "Região Rio Caeté",
    "TRAIRÃO": "Região Tapajós",
    "TUCUMÃ": "Região Araguaia",
    "TUCURUÍ": "Região Lago Tucuruí",
    "ULIANÓPOLIS": "Região Rio Capim",
    "URUARÁ": "Região Xingu",
    "VIGIA": "Região Guamá",
    "VISEU": "Região Rio Caeté",
    "VITÓRIA DO XINGU": "Região Xingu",
    "XINGUARA": "Região Araguaia",
    "ÁGUA AZUL DO NORTE": "Região Araguaia",
    "ÓBIDOS": "Região Baixo Amazonas",
}
